# Generated by Django 4.1.3 on 2022-12-09 22:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('accountNumber', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(1000000000000000)])),
                ('current_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(blank=True, max_length=6, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('accountNumber',), name='unique accountNumber'),
        ),
    ]
